### ISSUE TITLE
Additional Loader Error - Shop Template

### ISSUE THREAD

**Issue by Moataz-E** [scale-it/algo-builder-templates#36]
Hi,

I am facing an issue when trying to run the shop template.

**Replication Steps:**
1. Unboxing the shop template with `yarn run algob unbox-template shop ../dapp-shop`
2. `cd ../dapp-shop`
3. `yarn install`
4. `yarn start`

**Error:**
![image](https://user-images.githubusercontent.com/1480671/166502860-63af7464-6c06-48d0-a6e7-e7c1b21336a6.png)

**Comment by vuvoth** [comment]
Thank you for issue!

One of solution:

1. modify a filed in package.json 
```
 "browserslist": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ] 
```
2.  Run  `yarn cache clean --force`
3.  Run `rm -rf node_modules && rm -f yarn.lock && yarn`.
